version: '3.8'

services:
  spring-boot-app:
    image: openjdk:18
    container_name: spring-boot-app
    working_dir: /app
    volumes:
      - ./target/time-maker.jar:/app/time-maker.jar
    ports:
      - "8081:8080"  # Change the external port to 8081 (or another port)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    command: ["java", "-jar", "/app/time-maker.jar"]

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
